rename xddd
xdd

diff --git a/scripts/updater b/scripts/updater
--- a/scripts/updater
+++ b/scripts/updater
@@ -67,7 +67,7 @@ if [ "$dialog" == true ] && [ "$exists" == false ]; then
   value=false
   response=255
   while [ "$response" != 0 ] && [ "$response" != 1 ]; do
-    dialog --keep-tite --title "Updater" --yesno "Do you want to enable the Rosnehook auto updater?" 10 25 || {
+    dialog --keep-tite --title "Updater" --yesno "Do you want to enable the Darkerhook auto updater?" 10 25 || {
       response=$?
       continue
     }
@@ -88,7 +88,7 @@ if [ "$AUTO_UPDATER_ENABLED" == "true" ]; then
   fi
   AUTOUPDATER=true
   tui=false
-  echo -e "\033[1;34m \n \nAuto Updater: Updating Rosnehook in the background\n\033[0m"
+  echo -e "\033[1;34m \n \nAuto Updater: Updating Darkerhook in the background\n\033[0m"
 fi
 
 function performupdate() {
@@ -113,7 +113,7 @@ function performupdate() {
     git fetch --force --depth 1 origin || {
       echo -e "\033[1;33m\nFailed to pull from github! Trying alternative pull (legacy)\n\033[0m"
       git fetch --depth 1 || {
-        echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. https://github.com/RosneBurgerworks/rosnehook\n\033[0m"
+        echo -e "\033[1;31m\nFailed to pull from github! A reinstall is recommended. https://github.com/RosneBurgerworks/darkerhook\n\033[0m"
         exit 1
       }
     }
@@ -160,9 +160,9 @@ function performupdate() {
 
   #Create build folder in case it doesn't exist
   mkdir -p ./build
-  # Update Rosnehook
+  # Update Darkerhook
   pushd build && cmake .. && cmake --build . --target cathook -- -j"$(nproc --all)" || {
-    echo -e "\033[1;31m \n \nFailed to compile Rosnehook\n\033[0m"
+    echo -e "\033[1;31m \n \nFailed to compile Darkerhook\n\033[0m"
     exit 1
   }
   # Update data
@@ -175,7 +175,7 @@ function performupdate() {
     }
   }
   popd
-  echo -e "\n\033[1;34mRosnehook updated successfully\n\033[0m"
+  echo -e "\n\033[1;34mDarkerhook updated successfully\n\033[0m"
   rm -f ${LOCKFILE}
 }
 
